My_first_pull_request_
gilberthappi/Hello-world pull request #1
Opened 2023-07-04 23:00 UTC by gilberthappi

This pull request aims to improve the visual presentation and readability of this page. The following changes have been made:

Added appropriate heading tags (h1,.) to the page title and sections for better semantic structure.
Implemented CSS styles for headings, including color, to enhance their visibility and hierarchy.
Adjusted line spacing and paragraph indentation to improve the overall readability of the content.

2023-07-04 23:09 UTC, Efiamotu-1 requested changes
Hi @gilberthappi, 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 23:09 UTC, Efiamotu-1 commented on index.html
* [ ] I would kindly suggest you remove all the placeholder text describing what you need to do in each heading of the Readme file. This is just there as a guideline for what you need to do in each heading and it should be removed.
 
 - placeholder text like the following example below
 
 > Describe your project in 1 or 2 sentences.
 > Describe the tech stack and include only the relevant sections that apply to your project.
 > Describe between 1-3 key features of the application.
 > Describe how a new developer could make use of your project. e.t.c

2023-07-04 23:09 UTC, Efiamotu-1 commented on index.html
- [ ] Your MIT license is not configured properly please kindly follow this [link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)  to set it up properly :+1:

2023-07-04 23:09 UTC, Efiamotu-1 commented on index.html
- [ ] If your project does not have a live demo you can remove that section from your readme :+1:

2023-07-05 13:42 UTC, gilberthappi commented on index.html
RIGHT 
THANKS

2023-07-05 13:42 UTC, gilberthappi commented on index.html
RIGHT 
THANKS

2023-07-05 14:01 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @gilberthappi 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Correct use of GitHub Flow ✔
- All linter checks are passing ✔

 ## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 14:01 UTC, AbelG101 commented on index.html
- [ ] Ouch! please make sure you make the changes on the branch the pull request is for as I noticed you made the changes on the `master` branch instead of the `HTML-CSS-Branch` branch. ✔

2023-07-05 14:56 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @gilberthappi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Fair README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 14:56 UTC, Qoosim commented on README.md
> +This project is [MIT](./LICENSE)  licensed.
- [ ] You have no information in this file you referenced. The appropriate information is in the MIT.md  file. Kindly reference to that file and ensure you commit and push to the appropriate branch.

### ./LICENSE FILE
![license](https://github.com/gilberthappi/Hello-world/assets/26597432/10770236-5efb-4d6a-8c41-bca408f4b63b)

### ./MIT.md
![mit](https://github.com/gilberthappi/Hello-world/assets/26597432/6d7ecfca-39c5-4eba-b8a3-82a05f2956dd)

2023-07-05 14:56 UTC, Qoosim commented on index.html
> +</body>
- [OPTIONAL] It is required to give a class name to the `h1` element according to the project requirement and use that class name to style the content of the header.

### Project Requirement
![proj-rqt](https://github.com/gilberthappi/Hello-world/assets/26597432/2359a5f5-6c8c-418c-a4d5-064f4e5da5d3)

It should look something similar to this :point_down: 

```
    <h1 class="header">Hello Microverse</h1>
```

2023-07-05 15:43 UTC, Alusp approved these changes
Hi @gilberthappi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats](https://media.giphy.com/media/qx8pi39Lwm9Xm2audb/giphy.gif)

## Highlights
- [ ] Good Github Flow :green_circle: 
- [ ] Good PR Summary :green_circle: 
- [ ] No Linter Errors :green_circle: 
- [ ] Professional Readme Template used :green_circle: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 16:07 UTC, merged